# -*- coding: utf-8 -*-
"""Cópia de Aula 4 | Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MV74eajw8Qv8S_RUQCK71naQyLlS8twc

## Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

**Objetivo do Projeto**

O objetivo é realizar uma análise exploratória de dados sobre hábitos de saúde e bem-estar coletados por meio de um questionário.

A pesquisa foi realizada em outubro de 2025.

**Perguntas de Pesquisa**
* Qual é a frequência de atividade física entre os participantes?
* Qual é o consumo de frutas e bebidas açucaradas semanalmente?
* Existe uma relação entre a prática de atividade física e o consumo de alimentos saudáveis?
* Como variam os padrões de sono e o tempo de tela entre os participantes?
"""

import pandas as pd

dados = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vResfZtKfATsuGT-EgsyFoPaezv8XxIBx_PRpQRd-U3-uyIG2bQzA_-zmp9QEUhz2S6361yOTzsf6h9/pub?gid=373547015&single=true&output=csv")

dados